#!/bin/zsh

# Interactive search.
# Usage: `ff` or `ff <folder>`.
#
[[ -n $1 ]] && cd $1 # Go to the provided folder or noop
RG_DEFAULT_COMMAND="rg -i -l --hidden --no-ignore-vcs --glob '!**/.*/*'"

selected=$(
FZF_DEFAULT_COMMAND="rg --files -n --glob '!**/.*/*'" fzf \
  -m \
  -e \
  --ansi \
  --phony \
  --reverse \
  --bind "ctrl-a:select-all" \
  --bind "f12:execute-silent:(subl -b {})" \
  --bind "change:reload:$RG_DEFAULT_COMMAND {q} || true" \
  --preview "rg -i --pretty --context 2 --glob '!**/.*/*' {q} {}" | cut -d":" -f1,2
)

if [[ -n $selected ]]; then
  # Transform file:line format to +line file format for nvim
  nvim_args=()
  for selection in $selected; do
    if [[ $selection == *:* ]]; then
      file="${selection%:*}"
      line="${selection#*:}"
      nvim_args+=("+$line" "$file")
    else
      nvim_args+=("$selection")
    fi
  done
  nvim "${nvim_args[@]}"
fi
